# --- Storage ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gokso-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# --- Monolith Service ---
apiVersion: v1
kind: Service
metadata:
  name: gokso-service
spec:
  type: LoadBalancer
  selector:
    app: gokso
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9001
---
# --- Monolith Deployment (App + DB) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gokso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gokso
  template:
    metadata:
      labels:
        app: gokso
    spec:
      containers:
        # 1. PostgreSQL Container (Sidecar)
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "Sci$iK50"
            - name: POSTGRES_DB
              value: goksodb
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres-data

        # 2. Go Application Container
        - name: go-app
          image: absolutezero24/gokso-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: APP_NAME
              value: "gokso"
            - name: APP_ENV
              value: "production"
            - name: APP_PORT
              value: "9001"
            - name: APP_AUTO_MIGRATE # Integrated migration
              value: "true"
            - name: DB_HOST
              value: "localhost" # Connect to the sidecar via localhost
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "Sci$iK50"
            - name: DB_NAME
              value: "goksodb"
            - name: DB_PORT
              value: "5432"
          volumeMounts:
            - name: storage
              mountPath: /root/public/nas
              subPath: nas
            - name: storage
              mountPath: /root/public/uploads
              subPath: uploads
      
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: gokso-pvc
