apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gokso-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: gokso.scisi.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: gokso-backend-service
            port:
              number: 80
      - path: /public
        pathType: Prefix
        backend:
          service:
            name: gokso-backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gokso-frontend-service
            port:
              number: 80
